version: '3.8'

services:
  timetracker_app:
    image: timetracker-x64-linux
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      - APP_ENV=production
    volumes:
      - timetracker:/app/backend/data
volumes:
  timetracker: